services:
  dns:
    restart: always
    build: .
    ports:
      - "53:53/udp"
    environment:
      CRON_SCHEDULE: "5 4 * * *"
      DNS_PRIMARY: "1.0.0.1"
      DNS_SECONDARY: "1.1.1.1"
       # DNS_BLACKLIST: "https://gist.githubusercontent.com/danielchc/a99bdf0f70ddc6856e9804914c5d76c1/raw/"
      # Minimal blacklist
      DNS_BLACKLIST: "https://gist.githubusercontent.com/danielchc/24def75140394fd6de29a21aa730efa5/raw/"
    cap_add:
      - NET_ADMIN
